name: build
on:
  pull_request
jobs:
  bridgecrew-job:
    runs-on: ubuntu-latest
    name: bridgecrew-action
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run Bridgecrew action
        id: bridgecrew
        uses: bridgecrewio/bridgecrew-action@master
        with:
          api-key: ${{ secrets.BRIDGECREW_API_KEY }}
          directory: terraform/
